### ISSUE TITLE
Will kappa still be maintained after private modules are released for NPM?

### ISSUE THREAD

**Issue by augbog** [krakenjs/kappa#106]
I saw NPM is releasing [private-modules](https://www.npmjs.com/private-modules) so people can maintain their own private npm registries. I was wondering if this would affect kappa at all? Will it still be maintained? Or perhaps they are not related at all and address entirely different use-cases haha.

Please label this as question.

**Comment by jasisk** [comment]
Kappa will continue to be maintained. No worries there.

Personally, I see enough non-overlapping parts between kappa and npm's offerings (both private modules and npmE) to make all three products compelling.
