### ISSUE TITLE
Update kappa example to work with newest version of `good`

### ISSUE THREAD

**Issue by totherik** [krakenjs/kappa#89]
The current example reflects version ^3, which is no longer latest.

**Comment by jasisk** [comment]
Ok, a bit more complex than that.

`good@^4` introduced hapi as a peerDependency. `good-console@^3` has `good@^5` as a dependency.

In other words, the last working configuration for us is to have projects with kappa as a dependency also have `good@^3` and `good-console@^2`, setting the reporter to `good-console`.

To fix, we'll have to move the `good` dependency into kappa regardless of whether users register a reporter. Kind of a bummer but not horrible.
